Version 1 proceso PR19 Juntas de coordinacion diaria
MutateInc/MutateInc.github.io pull request #100
Opened 2022-04-26 21:58 UTC by jimmedto

2022-04-28 04:03 UTC, GlinkIsCoding requested changes
Bien en general Jim, gracias! Te dejo las correcciones a realizar.

2022-04-28 04:03 UTC, GlinkIsCoding commented on docs/Procesos/PR19.md
> +            Conectarse al canal de voz de Discord correspondiente al equipo en el horario establecido por el equipo
Punto final faltante.

2022-04-28 04:03 UTC, GlinkIsCoding commented on docs/Procesos/PR19.md
> +            Proyectar el plan de trabajo
Punto final.

2022-04-28 04:03 UTC, GlinkIsCoding commented on docs/Procesos/PR19.md
> +        <li>Registrar hora de inicio según el repositorio de métricas</li>
punto final.

2022-04-28 04:03 UTC, GlinkIsCoding commented on docs/Procesos/PR19.md
> +            <li>El líder del equipo de asegurar que se responden las 3 preguntas</li>
"debe de asegurar" y punto final.

2022-04-28 04:03 UTC, GlinkIsCoding commented on docs/Procesos/PR19.md
> +            <li>El líder del equipo debe cuestionar si se realizó trabajo fuera del plan</li>
Punto final.

2022-04-28 04:03 UTC, GlinkIsCoding commented on docs/Procesos/PR19.md
> +        <li>Registrar la hora de fin de la junta. Si la junta duró más de 15 minutos debe proponerse una mejora a este proceso.</li>
"...del fin de la junta."

2022-04-28 04:03 UTC, GlinkIsCoding commented on docs/Procesos/PR19.md
> +        <li>Los miembros del equipo deben resolver los impedimentos inmediatamente o hacer un plan para resolverlos y éste plan debe integrarse al plan de trabajo. El líder del equipo debe asegurar q
punto final.

2022-04-28 04:03 UTC, GlinkIsCoding commented on docs/Procesos/PR19.md
> +| 1.0     | Creación del proceso       | Nahim Medellín      | 26/04/22   |
Actualizar versión con correcciones.

2022-05-03 23:06 UTC, Heyestefii approved these changes

2022-05-04 17:58 UTC, GlinkIsCoding approved these changes

2022-05-04 17:58 UTC, merged