Update 1.3 GU14
MutateInc/MutateInc.github.io pull request #101
Opened 2022-04-28 16:47 UTC by JesusOlmosLarios

Se realizaron correcciones lógicas al documento con la finalidad de hacer la guía más comprensible

2022-04-29 04:58 UTC, GlinkIsCoding requested changes
unas cuantas correcciones de ortografía!

2022-04-29 04:58 UTC, GlinkIsCoding commented on docs/Guias/GU14.md
> +Utilizaremos la [GU11-Guía para Mantener una Trazabilidad Bidireccional de Requerimientos](https://mutateinc.github.io/Guias/GU11/) para obtener de esta forma una matriz que es capaz de determinar si
"...para obtener una matriz que es capaz..." eliminar **de esta forma**.

2022-04-29 04:58 UTC, GlinkIsCoding commented on docs/Guias/GU14.md
> +Se puede encontrar una plantilla de la Matríz de Trazabilidad en el siguiente [enlace](https://docs.google.com/spreadsheets/d/1fzVtNj_sg70hLxa0lR3XwFcB0ptDGkGWR44euACIPrM/edit?usp=sharing)
falta punto final.

2022-04-29 04:58 UTC, GlinkIsCoding commented on docs/Guias/GU14.md
> +Una vez que se empiece a llenar la matriz de trazabilidad, los requerimientos deberán de estar presentes en el Acta del Proyecto, esto con el fin de que los Socios formadores sepan el estado de los r
"...deberán estar presentes..."

2022-05-06 18:28 UTC, JesusOlmosLarios reviewed
Revisado y corregido

2022-05-06 18:47 UTC, GlinkIsCoding requested changes
1 nuevo detalle inyectado y yap

2022-05-06 18:47 UTC, GlinkIsCoding commented on docs/Guias/GU14.md
> +Se puede encontrar una plantilla de la Matríz de Trazabilidad en el siguiente [enlace](https://docs.google.com/spreadsheets/d/1fzVtNj_sg70hLxa0lR3XwFcB0ptDGkGWR44euACIPrM/edit?usp=sharing).
Matriz no lleva acento.

2022-05-19 03:34 UTC, Heyestefii approved these changes

2022-05-19 03:35 UTC, Heyestefii approved these changes

2022-05-19 23:59 UTC, GlinkIsCoding approved these changes

2022-05-19 23:59 UTC, merged