docs: creacion de definicion
MutateInc/MutateInc.github.io pull request #103
Opened 2022-05-02 16:40 UTC by jeduardocb

creacion de la definicion

2022-05-04 17:55 UTC, GlinkIsCoding requested changes
Les dejo las correcciones!

2022-05-04 17:55 UTC, GlinkIsCoding commented on docs/Definiciones/DE11.md
> +# DE11-Definición de Análisis y Resolución de Decisiones (DAR)
"del Análisis y la Resolución..."

2022-05-04 17:55 UTC, GlinkIsCoding commented on docs/Definiciones/DE11.md
> +- Apoyar a los equipos de desarrollo para que tomen las decisiones que aporten más valor a sus respectivos proyectos en base a los estándares definidos por CMMI en su área de “Decision Analysis and R
"...proyectos con base en los estándares definidos..."

2022-05-04 17:55 UTC, GlinkIsCoding commented on docs/Definiciones/DE11.md
> +- Todos los integrantes de MUTATE logren sus competencias que engloban la toma de decisiones CCMI antes del final de la semana 15.
"Lograr que todos los integrantes de MUTATE desarrollen las competencias que engloban la toma de decisiones CMMI antes del final de la semana 15."

2022-05-04 17:55 UTC, GlinkIsCoding commented on docs/Definiciones/DE11.md
> +## ¿Qué es Decision Analysis and Resolution?​
"... es el Análisis y la Resolución de Decisiones?"

2022-05-04 17:55 UTC, GlinkIsCoding commented on docs/Definiciones/DE11.md
> +Sacando la definición del manual de CMMI v1.3 (2010): "The purpose of Decision Analysis and Resolution is to analyze possible decisions using a formal evaluation process that evaluates identified alt
"Tomando la definición..."

2022-05-04 17:55 UTC, GlinkIsCoding commented on docs/Definiciones/DE11.md
> +## Práctica a Seguir​
"seguir" en minúscula

2022-05-04 17:55 UTC, GlinkIsCoding commented on docs/Definiciones/DE11.md
> +### Sub Prácticas
"Subprácticas"

2022-05-04 17:55 UTC, GlinkIsCoding commented on docs/Definiciones/DE11.md
> +2. Establecer y mantener los criterios para evaluar las alternativas, y la importancia relativa de estos criterios.
"... alternativas, así como la importancia..."

2022-05-04 17:55 UTC, GlinkIsCoding commented on docs/Definiciones/DE11.md
> +| 1.0     | Creación de definición | Eduardo Cadena, Miguel Marines, Carlos Ayala, Omar Molina| 02/05/2022 |
Actualizar versionado con correcciones.

2022-05-09 03:06 UTC, GlinkIsCoding requested changes
1 detalle porque no se corrigió por completo ! :)

2022-05-09 03:06 UTC, GlinkIsCoding commented on docs/Definiciones/DE11.md
> +- Apoyar a los equipos de desarrollo para que tomen las decisiones que aporten más valor a sus respectivos proyectos con base a los estándares definidos por CMMI en su área de “Decision Analysis and
no se realizó la corrección. "...proyectos con base `en` los estándares..."

2022-05-12 00:24 UTC, GlinkIsCoding approved these changes

2022-05-19 03:23 UTC, Heyestefii approved these changes

2022-05-19 03:23 UTC, merged