Docs Definición: Área PPQA
MutateInc/MutateInc.github.io pull request #104
Opened 2022-05-03 05:14 UTC by valeriagdlo

Definición de PPQA

2022-05-04 18:08 UTC, GlinkIsCoding requested changes
correcciones bro!

2022-05-04 18:08 UTC, GlinkIsCoding commented on docs/Definiciones/DE12.md
> +# DE12-ASEGURAMIENTO DE LA CALIDAD DEL PROCESO Y DEL PRODUCTO  (PPQA)
Usar mismo formato que el resto de las Definiciones en el título. (Mayúsculas y minúsculas)

2022-05-04 18:08 UTC, GlinkIsCoding commented on docs/Definiciones/DE12.md
> +Da soporte a la entrega de productos de alta calidad, proporcionando al personal del proyecto y a los gerentes, en todos los niveles, la visibilidad apropiada y la realimentación sobre los procesos y
"y a los gerentes (en todos los niveles) la visibilidad..."
"...asociados durante toda la vida..." quitar coma.

2022-05-04 18:08 UTC, GlinkIsCoding commented on docs/Definiciones/DE12.md
> +    2.-Informes de no conformidad.
Espacio después de guion

2022-05-04 18:08 UTC, GlinkIsCoding commented on docs/Definiciones/DE12.md
> +    3.-Acciones correctivas.
Espacio después de guion

2022-05-04 18:08 UTC, GlinkIsCoding commented on docs/Definiciones/DE12.md
> +    3.-Acciones correctivas.
Espacios después de guion

2022-05-06 18:20 UTC, valeriagdlo commented on docs/Definiciones/DE12.md
> +# DE12-ASEGURAMIENTO DE LA CALIDAD DEL PROCESO Y DEL PRODUCTO  (PPQA)
Listo :)

2022-05-06 18:20 UTC, valeriagdlo commented on docs/Definiciones/DE12.md
> +Da soporte a la entrega de productos de alta calidad, proporcionando al personal del proyecto y a los gerentes, en todos los niveles, la visibilidad apropiada y la realimentación sobre los procesos y
Ya quedaron las correcciones :)

2022-05-06 18:21 UTC, valeriagdlo commented on docs/Definiciones/DE12.md
> +    3.-Acciones correctivas.
Los espacios quedaron corregidos.

2022-05-06 18:40 UTC, GlinkIsCoding requested changes
1 detallito y ya:)

2022-05-06 18:40 UTC, GlinkIsCoding commented on docs/Definiciones/DE12.md
> +# DE12-Aseguramiento de la calidad del proceso del producto (PPQA)
"proceso y del producto..." le quitaste el y jeje

2022-05-06 18:40 UTC, GlinkIsCoding commented on docs/Definiciones/DE12.md
> +## ¿Qué hace PPQA ?
Y este no lo había visto, quitar el espacio antes del signo de interrogación de cierre.

2022-05-12 00:22 UTC, GlinkIsCoding approved these changes

2022-05-19 03:15 UTC, Heyestefii approved these changes

2022-05-19 03:19 UTC, merged