Fix/documentos/estandares/ramas
MutateInc/MutateInc.github.io pull request #106
Opened 2022-05-03 13:35 UTC by AlbertoMatuteB

2022-05-04 18:24 UTC, GlinkIsCoding requested changes
les dejo las correcciones c:

2022-05-04 18:24 UTC, GlinkIsCoding commented on docs/Estandares/ES01.md
> +`type` es el tipo de cambio que se está haciendo (de acuerdo a los estándares de [Conventional Commits v1.0.0](https://www.conventionalcommits.org/en/v1.0.0/#summary)) y puede ser uno de los siguient
"... por su frecuencia de uso):" quitar lo de mejor entendimiento y corregir frecuencia.

2022-05-04 18:24 UTC, GlinkIsCoding commented on docs/Estandares/ES01.md
> + Por ejemplo, diferentes tipos de scope para la wiki son:
"...la Wiki son:..."

2022-05-04 18:24 UTC, GlinkIsCoding commented on docs/Estandares/ES01.md
> +El scope para código sería la user story a la que pertenece.
"User Story"

2022-05-04 18:24 UTC, GlinkIsCoding commented on docs/Estandares/ES01.md
> +| 1.4     | Cambio a estándar                            | Alberto Matute     | 03/05/2022 |
Actualizar versionado con correcciones.

2022-05-04 18:24 UTC, GlinkIsCoding commented on docs/Politicas/PO02.md
> +- Todo requerimiento que se desee cambiar, deberá de seguir los lineamientos establecidos en el [Proceso de cambios a requisitos](../Procesos/PR10). Además de esto, no se aceptarán modificaciones de
"(cambios..." en minúscula.
"despliegue, apoyando el punto anterior" quitar 'esto'

2022-05-04 18:24 UTC, GlinkIsCoding commented on docs/Politicas/PO02.md
> +| 1.0     | Creación de la Política                       | Jesús Olmos Larios     | 02/04/2022 |
Actualizar versionadooo

2022-05-04 18:24 UTC, GlinkIsCoding commented on docs/Politicas/PO03.md
> +eficiente y responsable de los datos, además, garantizar que esos conjuntos de datos se preserven.
"de los datos. Además, garantizar que esos conjuntos..."

2022-05-04 18:24 UTC, GlinkIsCoding commented on docs/Politicas/PO03.md
> +Toda aquella información que se relaciona con nuestra persona y que nos identifica o nos hace identificables.
"Toda información..."

2022-05-04 18:24 UTC, GlinkIsCoding commented on docs/Politicas/PO03.md
> +- Los datos solo podrán ser accesados desde dispositivos personales de los integrantes del departamento. En ningún caso de algún dispositivo de uso público.
"caso desde algún dispositivo..."

2022-05-04 18:24 UTC, GlinkIsCoding commented on docs/Politicas/PO03.md
> +| 1.0     | Creación de la plantilla     | Eduardo Cadena | 4/20/2022  |
"Creación de la política" y actualizar versionado

2022-05-06 15:22 UTC, AlbertoMatuteB commented on docs/Estandares/ES01.md
> +| 1.4     | Cambio a estándar                            | Alberto Matute     | 03/05/2022 |
Todavia no esta en linea base no hace falta versionar con ortografia si las faltas se encontraron en la revision

2022-05-06 16:37 UTC, AlbertoMatuteB commented
lo voy a cerrar prefiero que se haga el merge despues de la retro del SCAMPI

2022-05-19 14:07 UTC, Heyestefii approved these changes

2022-05-19 23:58 UTC, GlinkIsCoding approved these changes

2022-05-19 23:59 UTC, merged