Creación de proceso 16
MutateInc/MutateInc.github.io pull request #108
Opened 2022-05-05 09:53 UTC by sebasr2599

Se crea el proceso de conversión de retroalimentación a áreas de trabajo

2022-05-05 23:06 UTC, GlinkIsCoding requested changes
cambios ortográficos y de redacción :)

2022-05-05 23:06 UTC, GlinkIsCoding commented on docs/Procesos/PR16.md
> +          <li>Responsable de minuta</li>
punto final.

2022-05-05 23:06 UTC, GlinkIsCoding commented on docs/Procesos/PR16.md
> +          <li>Cualquier otra persona que tenega notas</li>
"tenga" y punto final.

2022-05-05 23:06 UTC, GlinkIsCoding commented on docs/Procesos/PR16.md
> +      Determinar si la retroalimentación dada es de uso
punto final.

2022-05-05 23:06 UTC, GlinkIsCoding commented on docs/Procesos/PR16.md
> +            <li>Asignar algun responsable de tomar la retroalimentación para ser aplicada a algun area de trabajo</li>
"a algún área de trabajo." y punto final.

2022-05-05 23:06 UTC, GlinkIsCoding commented on docs/Procesos/PR16.md
> +            <li>Categorizar la prioridad de esta retroalimentación</li>
punto final.

2022-05-05 23:06 UTC, GlinkIsCoding commented on docs/Procesos/PR16.md
> +            <li>Tomar la retroalimentación para poder ser convertida en tareas en los planes de proyecto adecuados</li>
"para que pueda ser convertida en..." y punto final.

2022-05-05 23:06 UTC, GlinkIsCoding commented on docs/Procesos/PR16.md
> +      <td>Conversion a área de trabajo</td>
"Conversión"

2022-05-05 23:06 UTC, GlinkIsCoding commented on docs/Procesos/PR16.md
> +            <li>Comunicar con los interesados sobre estos cambios y áreas a trabajar</li>
punto final.

2022-05-05 23:06 UTC, GlinkIsCoding commented on docs/Procesos/PR16.md
> +-   Registro en la <a href="https://docs.google.com/spreadsheets/d/1EMzUz6Mpc0o19nuCAvWy__Pn0Ix_4aosfGUQ-tKn-gc/edit?usp=sharing" target="_blank">matriz de retroalimentación</a> del departamento
puntos finales.

2022-05-30 17:52 UTC, closed without merging

2022-05-30 17:52 UTC, AlbertoMatuteB commented
26 dias sin ser actualizado