feat(Validacion): :sparkles: Definicion de Validacion
MutateInc/MutateInc.github.io pull request #110
Opened 2022-05-06 02:49 UTC by SamOctGonzAzpeitia

2022-05-06 03:12 UTC, GlinkIsCoding requested changes
correcciones ortográficas!

2022-05-06 03:12 UTC, GlinkIsCoding commented on docs/Definiciones/DE12.md
> +# DE12-Definición de Validación
"de la Validación (VAL)". usar mismo formato que otras definiciones.

2022-05-06 03:12 UTC, GlinkIsCoding commented on docs/Definiciones/DE12.md
> +La validación demuestra que el producto, tal cual se proporciona, cumplirá con su uso previsto
punto final.

2022-05-06 03:12 UTC, GlinkIsCoding commented on docs/Definiciones/DE12.md
> +Las actividades de validación se pueden aplicar a todos los aspectos del producto en cualquiera de sus entornos
punto final.

2022-05-06 03:12 UTC, GlinkIsCoding commented on docs/Definiciones/DE12.md
> +## Metas generales y Prácticas de la Gestión de PPQA
de PPQA?

2022-05-06 03:12 UTC, GlinkIsCoding commented on docs/Definiciones/DE12.md
> +		Sub Prácticas:
"Subprácticas:"

2022-05-06 03:12 UTC, GlinkIsCoding commented on docs/Definiciones/DE12.md
> +Seleccionar los métodos de evaluación para la validación
punto final.

2022-05-06 03:12 UTC, GlinkIsCoding commented on docs/Definiciones/DE12.md
> +Sub Prácticas
"Subprácticas:"

2022-05-06 03:12 UTC, GlinkIsCoding commented on docs/Definiciones/DE12.md
> +Definir las secciones que sean necesarias para que el asset sirva como introducción y agregue valor a un área.
Esto no es de la plantilla?

2022-05-06 03:12 UTC, GlinkIsCoding commented on docs/Definiciones/DE12.md
> +Sub Prácticas
"Subprácticas:"

2022-05-06 03:12 UTC, GlinkIsCoding commented on docs/Definiciones/DE12.md
> + Evaluar el diseño a medida que madura en el contexto del entorno.
espacio extra al inicio.

2022-05-06 03:12 UTC, GlinkIsCoding commented on docs/Definiciones/DE12.md
> +Identificar los productos y los componentes de producto que no funcionan adecuadamente en base a los criterios de validación establecidos.
"...adecuadamente con base en los criterios..."

2022-05-06 03:12 UTC, GlinkIsCoding commented on docs/Definiciones/DE12.md
> + Registrar los resultados del análisis e identificar cuestiones.
Espacios extra al principio

2022-05-12 00:18 UTC, GlinkIsCoding approved these changes
correcciones ortográficas!

2022-05-17 03:04 UTC, Heyestefii approved these changes

2022-05-17 03:05 UTC, merged