docs(PPQA): :memo: Plantilla PPQA
MutateInc/MutateInc.github.io pull request #111
Opened 2022-05-09 00:55 UTC by valeriagdlo

Se añadió la plantilla de PPQA

2022-05-09 03:11 UTC, GlinkIsCoding requested changes
algunos typos!

2022-05-09 03:11 UTC, GlinkIsCoding commented on docs/Plantillas/PL12.md
> +Crear un estándar para la creación de adutirorías de items de trabajo y de procesos.
auditorías está mal escrito.

2022-05-09 03:11 UTC, GlinkIsCoding commented on docs/Plantillas/PL12.md
> +Puedes encontrarla siguiendo siguiente path:
"...siguiendo el siguiente..."

2022-05-09 03:11 UTC, GlinkIsCoding commented on docs/Plantillas/PL12.md
> +Áreas de proceso (CMMI)- PPQA - Plantilla de auditorías.
espacio después de CMMI (por consistencia)

2022-05-09 03:11 UTC, GlinkIsCoding commented on docs/Procesos/PR01.md
> +> Se sugiere consutar la [Guía de auditorías](../Guias/GU02.md) para solucionar dudas.
"consultar"

2022-05-09 03:11 UTC, GlinkIsCoding commented on docs/Procesos/PR01.md
> +> Se sugiere consutar la [Plantilla de auditorías ](../Plantillas/PL12.md) para estandarizar las auditorías.
"consultar"

2022-05-10 21:05 UTC, valeriagdlo commented on docs/Plantillas/PL12.md
> +Crear un estándar para la creación de adutirorías de items de trabajo y de procesos.
Listo :)

2022-05-10 21:05 UTC, valeriagdlo commented on docs/Plantillas/PL12.md
> +Puedes encontrarla siguiendo siguiente path:
Listoooo :)

2022-05-10 21:06 UTC, valeriagdlo commented on docs/Plantillas/PL12.md
> +Áreas de proceso (CMMI)- PPQA - Plantilla de auditorías.
Ya quedó :)

2022-05-10 21:06 UTC, valeriagdlo commented on docs/Procesos/PR01.md
> +> Se sugiere consutar la [Guía de auditorías](../Guias/GU02.md) para solucionar dudas.
Listo :)

2022-05-10 21:06 UTC, valeriagdlo commented on docs/Procesos/PR01.md
> +> Se sugiere consutar la [Plantilla de auditorías ](../Plantillas/PL12.md) para estandarizar las auditorías.
Listo :)

2022-05-12 00:11 UTC, GlinkIsCoding approved these changes

2022-05-17 03:01 UTC, Heyestefii approved these changes

2022-05-19 03:16 UTC, merged