Architecture casa mosaico
MutateInc/MutateInc.github.io pull request #15
Opened 2022-03-02 19:11 UTC by santyarellano

Primer boceto de descripción básica de necesidades (sección de resumen) y sección de team knowledge.

2022-03-03 01:15 UTC, BernardoEstrada requested changes

2022-03-03 01:15 UTC, BernardoEstrada commented on docs/Arquitectura/Casa Mosaico/TeamKnowledge.md
> +<br>
En archivos MD no se aceptan tags abiertas de html, usa `<br />` o quita el br y solo pon un enter (deberia ser el mismo resultado)

2022-03-03 17:32 UTC, coronapl commented
También, sugiero que este tipo de documentación esté en el Manual de arquitectura del equipo y no el Manual de operaciones del departamento.

2022-03-03 21:44 UTC, BernardoEstrada commented
> También, sugiero que este tipo de documentación esté en el Manual de arquitectura del equipo y no el Manual de operaciones del departamento.

@EricTorres27 @AlbertoMatuteB

2022-03-04 00:21 UTC, santyarellano commented on docs/Arquitectura/Casa Mosaico/TeamKnowledge.md
> +<br>
gracias :)

2022-03-04 00:40 UTC, BernardoEstrada approved these changes

2022-03-04 00:40 UTC, MartinNoboa approved these changes

2022-03-04 00:40 UTC, merged