Update/guia pp
MutateInc/MutateInc.github.io pull request #41
Opened 2022-03-15 23:17 UTC by FVargas4

2022-03-16 03:20 UTC, coronapl commented
En general, se ve bastante bien. Creo que los procesos están excelentes y aportan mucho valor. Algunas sugerencias:

- El proceso para redactar user stories no está siguiendo la plantilla de proceso.
- Está padre las mejoras que le hicieron a la plantilla de proceso (nada más checar lo de los autores), pero creo que es importante hacer las modificaciones en la plantilla y en la guía.
- Me gusta la idea de usar tablas en html, ¿lo modificamos en la plantilla también?
- Checar los comentarios adicionales.

2022-03-16 22:16 UTC, jeduardocb approved these changes

2022-03-16 23:21 UTC, coronapl requested changes

2022-03-17 00:07 UTC, FVargas4 reviewed
La corrección del proceso y la guía será pusheada en unos minutos.

2022-03-17 01:42 UTC, FVargas4 reviewed
Todas las observaciones fueron resueltas.

2022-03-17 03:23 UTC, coronapl approved these changes

2022-03-17 03:25 UTC, merged