Creacion de documento con enlaces a plantillas para planes de trabajo
MutateInc/MutateInc.github.io pull request #71
Opened 2022-03-28 22:50 UTC by FVargas4

Se corrigió un enlace en el proceso de definición de planes y se creó un documento con los enlaces a las plantillas de los planes de trabajo. Estas plantillas son totalmente modificables por si pueden checarlas y proponer cambiar/agregar algo en ellas.

2022-03-29 02:27 UTC, coronapl commented
- Revisar el título del PR para seguir el estándar de CM
- Tiene conflictos

2022-03-29 21:38 UTC, AlbertoMatuteB requested changes
https://docs.google.com/spreadsheets/d/1FzfJd_yahKMj8yLV8VuqbcArkBtyAe5-AVvSRLDyzM8/edit?usp=sharing

Nada mas falta cambiar en el archivo de PL10 todavia en el titulo dice PL20

2022-03-29 23:57 UTC, MartinNoboa approved these changes

2022-03-30 00:02 UTC, FVargas4 reviewed
Errores corregidos, gracias por la ayuda.

2022-03-30 15:35 UTC, AlbertoMatuteB approved these changes
https://docs.google.com/spreadsheets/d/1FzfJd_yahKMj8yLV8VuqbcArkBtyAe5-AVvSRLDyzM8/edit#gid=1420001587

se valido PL10

2022-03-30 19:03 UTC, merged

2022-03-30 19:03 UTC, FVargas4 commented
Gracias a por la retro.