Feat/ma/agregar contenido
MutateInc/MutateInc.github.io pull request #99
Opened 2022-04-26 06:09 UTC by MartinNoboa

2022-04-26 15:33 UTC, AlbertoMatuteB commented on docs/Definiciones/DE10.md
> +# DE05-Definición Medición y Análisis (MA)
cambiar nombre a DE10

2022-04-26 15:59 UTC, MartinNoboa commented on docs/Definiciones/DE10.md
> +# DE05-Definición Medición y Análisis (MA)
Completo

2022-04-28 03:58 UTC, GlinkIsCoding requested changes
Les dejo las correcciones a realizar!

2022-04-28 03:58 UTC, GlinkIsCoding commented on docs/Definiciones/DE10.md
> +# DE10-Definición Medición y Análisis (MA)
Cambiar a "`...Definición de la Medición...`" para consistencia con otros archivos.

2022-04-28 03:58 UTC, GlinkIsCoding commented on docs/Definiciones/DE10.md
> +## Propósito
Por qué hay dos encabezados de propósito?

2022-04-28 03:58 UTC, GlinkIsCoding commented on docs/Guias/GU18.md
> +Orientar a los involucrados a entender las métricas que se van a medir y su valor para los equipos y departamento.
"involucrados en entender"

"los equipos y el departamento."

2022-04-28 03:58 UTC, GlinkIsCoding commented on docs/Guias/GU18.md
> +    - Cada equipo definirá las tareas a realizar para lograr completar los objetivos de su proyecto y se les asignará un porcentaje de valor basado en: [Número de completadas/Número de tareas totales
falta punto final.

2022-04-28 03:58 UTC, GlinkIsCoding commented on docs/Guias/GU18.md
> +    - Cada equipo debe definir “Milestones de porcentaje completados” por fecha en base a los milestones de la planeación. De esta forma podremos saber dónde debería estar el proyecto.
"por fecha con base en los milestones"

2022-04-28 03:58 UTC, GlinkIsCoding commented on docs/Guias/GU18.md
> +- **Porcentaje de asistencia (Semanal. dónde y cómo).**
(Semanal. Dónde y cómo.)

faltan puntos y mayúscula para coherencia de formato

2022-04-28 03:58 UTC, GlinkIsCoding commented on docs/Guias/GU18.md
> +    - Siguiendo la política de asistencias y juntas departamentales, cada equipo así como el departamento deberán tomar asistencia contando el número de integrantes presentes, el número de integrante
"Número del total de integrantes * 100", en ambos usos de la frase

2022-04-28 03:58 UTC, GlinkIsCoding commented on docs/Guias/GU18.md
> +    - Se utilizará la [plantilla de asistencias departamental](https://docs.google.com/spreadsheets/d/1ZZD7dBKOD3rF1oOEzCjpLDWVHZrEiovCIKojgXc_mhg/edit#gid=0).
falta punto final.

2022-04-28 03:58 UTC, GlinkIsCoding commented on docs/Guias/GU18.md
> +    - Se llevará un rastreo individual por miembro del equipo de horas reales dedicadas al equipo y al departamento de está forma se podrá analizar el desempeño por parte de cada integrante, con esto
"departamento. De esta forma se podrá analizar..."

"por parte de cada integrante. Con esto se puede analizar..."

2022-04-28 03:58 UTC, GlinkIsCoding commented on docs/Guias/GU18.md
> +    - Cada equipo deberá rastrear los defectos detectados, su fase de detección y fase de inyección al igual que la acción a tomar para mitigarlos. De esta forma se podrá entender la calidad del proy
"datos históricos."

2022-04-28 03:58 UTC, GlinkIsCoding commented on docs/Guias/GU18.md
> +    - Error de estimación (SPI) =  (Porcentaje de plan completado/Porcentaje de plan estimado) esto nos ayudará a entender el avance de cada proyecto basado en la planificación.
"estimado). Esto nos ayudará..."

2022-04-28 03:58 UTC, GlinkIsCoding commented on docs/Guias/GU18.md
> +    - Desviación del plan actual (CPI) = (Porcentaje de plan completado/ Horas reales) Esto nos ayudará entender el valor obtenido del tiempo invertido.
"reales). Esto..."

2022-04-28 03:58 UTC, GlinkIsCoding commented on docs/Guias/GU18.md
> +| 1.1     | Actualización de guía   |   MA           | 25/04/2022 |
Actualizan la versión con las correcciones porfi.

2022-04-29 04:55 UTC, GlinkIsCoding requested changes
en la corrección solo 1 nuevo error

2022-04-29 04:55 UTC, GlinkIsCoding commented on docs/Guias/GU18.md
> +    - Se llevará un rastreo individual por miembro del equipo de horas reales dedicadas al equipo y al departamento. De está forma se podrá analizar el desempeño por parte de cada integrante. Con est
"De esta forma..." no lleva acento

2022-05-19 03:16 UTC, Heyestefii approved these changes

2022-05-19 03:21 UTC, merged